create table IF NOT EXISTS  fournisseur (id bigint generated by default as identity, nom varchar(255), reference varchar(255), primary key (id));
create table IF NOT EXISTS produit (id bigint generated by default as identity, availability integer, description varchar(255), hauteur float not null, largeur float not null, longueur float not null, nom varchar(255), prix_unitaire float, reference varchar(255), fournisseur_id bigint, primary key (id));
alter table produit add constraint IF NOT EXISTS FKayuabstor0gbpqp7stdcqwnte foreign key (fournisseur_id) references fournisseur;
